### PR TITLE
fix: Do not show index page if not authenticated

### PR DESCRIPTION
**Pull request by peeyalk**
Reverts Suchica/polygonHR#29

### CODE REVIEW

**Comment by hiroshinishio** [comment]
@peeyalk i have checked diff, so nothing changed after all??

**Comment by peeyalk** [comment]
> @peeyalk i have checked diff, so nothing changed after all??

what do you mean by nothing changed?
With this PR you won't be able to see the index page if not logged in.

**Comment by hiroshinishio** [comment]
I mean comparing to first pr https://github.com/Suchica/polygonHR/pull/28, it seems nothing changed but I just wanna confirm it with you. If so, just curious why you asked me to revert PR https://github.com/Suchica/polygonHR/pull/28 ?

**Comment by peeyalk** [comment]
> @peeyalk I mean comparing to first pr #28, it seems nothing changed but I just wanna confirm it with you. If so, just curious why you asked me to revert PR #28 ?

I thought the firebase error was caused by this PR

**Comment by hiroshinishio** [comment]
Ah I see, then the error was not related to this PR so I will approve it.

**Review by hiroshinishio — APPROVED** [review]

**Pull request merged**
